<?php
// Lab Number: 8
// Program Name: Database credentials
// Author Name: Matthew Casiro
// Author Email: mattcasiro@gmail.com
// Submission Date: Feb 29 2016
// Est. Time to Complete: 7 hours
// Act. Time to Complete: 6.5 hours
// Program Description: Credentials to connect to db server
// How to Run Program: navigate to:
//      deepblue.cs.camosun.bc.cs/~cst583/comp170/ass8/
// Files Required to Run: ass8Model.inc, ass8Controller.php, ass8ToXml.inc
//      ass8View.xsl, index.html, form.css

$host = "localhost";
$login = "170user";
$pwd = "phphasclass";
$dbID = "comp170";
?>